# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#
NAME: Rails Stripe Membership Saas
TYPE: Item
SLOGAN: Welcome to Ruby Software As A Service
DESC: Follow your favorite Items
ABOUT_PAGE: Url for an About Page
CONTACT_PAGE: Url for a Contact Page
FEATURES: []
GMAIL_USERNAME: Your_Username
GMAIL_PASSWORD: Your_Password
ADMIN_NAME: Admin User
ADMIN_FIRST_NAME: Admin
ADMIN_LAST_NAME: User
ADMIN_EMAIL: user@example.com
ADMIN_PASSWORD: changeme
ROLES: [admin, silver, gold, platinum]
RAILS_SECRET_KEY: '256 bit key'
DEVISE_SECRET_KEY: '256 bit key'
STRIPE_API_KEY: Your_Stripe_API_key
STRIPE_PUBLIC_KEY: Your_Stripe_Public_Key
AMAZON_ACCESS_KEY: Your_Amazon_Access_Key
AMAZON_SECRET_KEY: Your_Amazon_Secret_Key
GITHUB_OWNER: 'bastosmichael'
GITHUB_REPO: 'rails-stripe-membership-saas'
GITHUB_TOKEN: '40 bit key'